// Package evolution provides the skill self-evolution system for Wukong.
// It captures execution traces from skill sub-agents, analyzes failures
// via an LLM, and automatically patches SKILL.md files for continuous
// improvement.
package evolution

import (
	"time"
)

// ExecutionTrace records the complete trace of a single skill execution.
// It is aggregated from the event stream emitted during a skill delegate
// invocation and serves as the primary input for evolution analysis.
type ExecutionTrace struct {
	// SkillName is the name of the skill that was executed
	// (e.g., "code-reviewer").
	SkillName string `json:"skill_name"`
	// SkillFile is the path to the SKILL.md file on disk.
	SkillFile string `json:"skill_file"`
	// SessionID is the session in which the skill was invoked.
	SessionID string `json:"session_id"`
	// UserID is the user who triggered the execution.
	UserID string `json:"user_id"`
	// StartTime is when the skill execution began.
	StartTime time.Time `json:"start_time"`
	// EndTime is when the skill execution completed.
	EndTime time.Time `json:"end_time"`
	// Duration is the total execution duration.
	Duration time.Duration `json:"duration"`
	// ToolCalls is the ordered sequence of tool calls made during
	// execution, including their arguments, results, and errors.
	ToolCalls []ToolCallRecord `json:"tool_calls"`
	// LLMCalls is the number of LLM API calls made during execution.
	LLMCalls int `json:"llm_calls"`
	// Error is the first terminal error encountered, if any.
	Error string `json:"error,omitempty"`
	// ErrorCount is the total number of tool-call errors
	// (including retried calls).
	ErrorCount int `json:"error_count"`
	// FinalOutput is the last assistant response text from the skill.
	FinalOutput string `json:"final_output"`
	// OutputLength is the character length of FinalOutput.
	OutputLength int `json:"output_length"`
	// Success indicates whether the skill completed without errors
	// and produced a non-empty output.
	Success bool `json:"success"`
	// QualityScore is a heuristic quality score (0.0-1.0) based on
	// output length, error count, and tool call diversity.
	QualityScore float64 `json:"quality_score"`
}

// ToolCallRecord records a single tool invocation within a skill execution.
type ToolCallRecord struct {
	// Name is the tool name (e.g., "file_read", "execute_command").
	Name string `json:"name"`
	// Args is the JSON-encoded arguments passed to the tool.
	Args string `json:"args"`
	// Result is the tool's output (truncated to 4KB for storage).
	Result string `json:"result"`
	// Error is any error returned by the tool, empty on success.
	Error string `json:"error,omitempty"`
	// Duration is the wall-clock time of this tool call.
	Duration time.Duration `json:"duration"`
	// Sequence is the order of this call within the trace (0-indexed).
	Sequence int `json:"sequence"`
	// Retried indicates whether this call was a retry attempt.
	Retried bool `json:"retried"`
}

// PatchSuggestion is generated by an LLM analyzer when it determines
// that a skill's instruction can be improved to reduce future errors.
type PatchSuggestion struct {
	// SkillName matches the skill being patched.
	SkillName string `json:"skill_name"`
	// Reason explains why the patch is needed (what problem was found).
	Reason string `json:"reason"`
	// ProblemType categorizes the issue:
	//   - "missing_prerequisite": the skill lacks a necessary step
	//   - "outdated_instruction": instructions reference deprecated APIs
	//   - "parameter_error": default or example parameters are wrong
	//   - "ambiguous_wording": unclear instructions confuse the model
	//   - "missing_error_handling": no guidance on handling failures
	ProblemType string `json:"problem_type"`
	// DiffContent is the unified diff patch content to apply to the
	// SKILL.md body (Markdown section, excluding YAML front matter).
	DiffContent string `json:"diff_content"`
	// UpdatedSections lists which Markdown sections were modified.
	UpdatedSections []string `json:"updated_sections,omitempty"`
	// Confidence is the LLM's self-reported confidence in this patch
	// (0.0-1.0). Patches below MinConfidence are rejected.
	Confidence float64 `json:"confidence"`
	// GeneratedAt is the timestamp when the patch was generated.
	GeneratedAt time.Time `json:"generated_at"`
}

// EvolutionRecord is persisted to the SQLite evolution_history table
// after each evolution analysis cycle (whether or not a patch was applied).
type EvolutionRecord struct {
	// ID is the auto-increment primary key.
	ID int64 `json:"id"`
	// SkillName is the skill that was analyzed.
	SkillName string `json:"skill_name"`
	// SessionID links back to the session that triggered analysis.
	SessionID string `json:"session_id"`
	// TraceJSON is the JSON-serialized ExecutionTrace for audit.
	TraceJSON string `json:"trace_json"`
	// HasIssue indicates whether the analyzer found an issue.
	HasIssue bool `json:"has_issue"`
	// PatchApplied indicates whether a patch was generated and applied.
	PatchApplied bool `json:"patch_applied"`
	// PatchReason is the reason from PatchSuggestion (if any).
	PatchReason string `json:"patch_reason,omitempty"`
	// PatchConfidence is the confidence score (if a patch was generated).
	PatchConfidence float64 `json:"patch_confidence,omitempty"`
	// VersionBefore is the SKILL.md version number before patching.
	VersionBefore int `json:"version_before"`
	// VersionAfter is the SKILL.md version number after patching
	// (equal to VersionBefore if no patch was applied).
	VersionAfter int `json:"version_after"`
	// CreatedAt is the record creation timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// SkillVersion represents a historical snapshot of a SKILL.md file
// stored in the version backup directory.
type SkillVersion struct {
	// ID is the auto-increment primary key.
	ID int64 `json:"id"`
	// SkillName is the skill this version belongs to.
	SkillName string `json:"skill_name"`
	// VersionNumber is the sequential version number (1, 2, 3...).
	VersionNumber int `json:"version_number"`
	// BackupPath is the absolute path to the backup file
	// (e.g., ".wukong_agent_skills/my-skill/SKILL.v003.md").
	BackupPath string `json:"backup_path"`
	// FileHash is the SHA-256 hex digest of the backup file.
	FileHash string `json:"file_hash"`
	// PatchReason is the reason for the change (from PatchSuggestion).
	PatchReason string `json:"patch_reason,omitempty"`
	// CreatedAt is when this version was created.
	CreatedAt time.Time `json:"created_at"`
}
