package wecom

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/km269/wukong/internal/config"
	"github.com/km269/wukong/internal/gateway"
	"github.com/km269/wukong/internal/util"
	"trpc.group/trpc-go/trpc-agent-go/event"
)

// WeComSender handles sending replies to WeCom, supporting both
// passive (direct JSON response) and streaming modes.
type WeComSender struct {
	cfg    *config.WeComChannelConfig
	client *http.Client
	token  *WeComTokenManager
}

// NewWeComSender creates a new WeComSender.
func NewWeComSender(cfg *config.WeComChannelConfig) *WeComSender {
	return &WeComSender{
		cfg: cfg,
		client: &http.Client{
			Timeout: 30 * time.Second,
		},
		token: NewWeComTokenManager(cfg),
	}
}

// SendTextReply prepares a passive text reply in JSON format.
// The actual HTTP response is written by the gateway handler.
func (ws *WeComSender) SendTextReply(
	ctx context.Context,
	msg *gateway.GatewayMessage,
	content string,
) error {
	if content == "" {
		content = "处理完成。"
	}

	// Truncate if too long for WeCom.
	maxLen := ws.cfg.MaxMessageLength
	if maxLen <= 0 {
		maxLen = 2048
	}
	if len([]rune(content)) > maxLen {
		content = truncateText(content, maxLen)
	}

	reply := &WeComReply{
		MsgType: "text",
		Text: &WeComReplyText{
			Content: content,
		},
	}

	data, err := json.Marshal(reply)
	if err != nil {
		return fmt.Errorf("wecom: marshal reply: %w", err)
	}

	_ = msg
	_ = ctx
	util.Logger.Debug("wecom: reply prepared",
		slog.Int("length", len(data)),
		slog.String("preview",
			string(data[:min(len(data), 80)])))

	return nil
}

// SendStreamReply sends the agent's response as a WeCom streaming
// message. This is the recommended approach for real-time display.
//
// Streaming flow:
//  1. Collect agent event content
//  2. If a stream_id is present on the request, do incremental
//     updates; otherwise send as a single message.
//
// For full streaming support with the WeCom streaming API, see the
// SendStreamingUpdates method below.
func (ws *WeComSender) SendStreamReply(
	ctx context.Context,
	msg *gateway.GatewayMessage,
	events <-chan *event.Event,
) error {
	// Collect all streaming content from agent events.
	var builder strings.Builder

	for evt := range events {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		if evt.Error != nil {
			util.Logger.Error("wecom: stream error",
				slog.String("error", evt.Error.Message))
			continue
		}

		if evt.Response != nil &&
			len(evt.Response.Choices) > 0 {
			choice := evt.Response.Choices[0]
			delta := choice.Delta.Content
			if delta != "" {
				builder.WriteString(delta)
			}
		}

		if evt.IsRunnerCompletion() {
			break
		}
	}

	content := builder.String()
	if content == "" {
		content = "处理完成。"
	}

	// Truncate if needed.
	maxLen := ws.cfg.MaxMessageLength
	if maxLen <= 0 {
		maxLen = 2048
	}
	if len([]rune(content)) > maxLen {
		content = truncateText(content, maxLen)
	}

	// If ResponseURL is available, send as proactive API message.
	if msg.ResponseURL != "" {
		return ws.sendProactiveReply(ctx, msg, content)
	}

	// Fallback: return content for passive reply (gateway handles).
	_ = content
	util.Logger.Debug("wecom: stream reply completed",
		slog.Int("content_length", len(content)))

	return nil
}

// SendStreamingUpdates sends incremental streaming updates to WeCom
// via the aibot/stream/* API endpoints. This requires a valid
// access_token.
//
// The stream_id is generated by the caller (typically a UUID) and
// used to track the streaming message across updates.
func (ws *WeComSender) SendStreamingUpdates(
	ctx context.Context,
	msg *gateway.GatewayMessage,
	events <-chan *event.Event,
) error {
	token, err := ws.token.GetAccessToken()
	if err != nil {
		return fmt.Errorf(
			"wecom: get access token: %w", err)
	}
	if token == "" {
		// No token configured; fall back to simple reply.
		return ws.SendStreamReply(ctx, msg, events)
	}

	streamID := generateStreamID(msg)
	var builder strings.Builder
	var lastSendLen int
	updateInterval := time.NewTicker(1 * time.Second)
	defer updateInterval.Stop()

	sendStreamUpdate := func(content string, finish bool) error {
		if content == "" && !finish {
			return nil
		}
		return ws.callStreamUpdate(
			ctx, token, streamID, content, finish)
	}

	// Start a stream placeholder.
	_ = ws.callStreamSend(ctx, token, streamID)

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()

		case evt, ok := <-events:
			if !ok {
				// Channel closed; finish stream.
				_ = sendStreamUpdate(builder.String(), true)
				return nil
			}

			if evt.Error != nil {
				continue
			}

			if evt.Response != nil &&
				len(evt.Response.Choices) > 0 {
				delta := evt.Response.Choices[0].Delta.Content
				if delta != "" {
					builder.WriteString(delta)
				}
			}

			if evt.IsRunnerCompletion() {
				_ = sendStreamUpdate(builder.String(), true)
				return nil
			}

		case <-updateInterval.C:
			currentLen := builder.Len()
			if currentLen > lastSendLen {
				delta := builder.String()[lastSendLen:]
				if delta != "" {
					_ = sendStreamUpdate(delta, false)
					lastSendLen = currentLen
				}
			}
		}
	}
}

// callStreamSend creates a new stream message via the WeCom API.
// POST /cgi-bin/aibot/stream/send?access_token=TOKEN
func (ws *WeComSender) callStreamSend(
	ctx context.Context,
	token, streamID string,
) error {
	if token == "" {
		return nil
	}

	reqBody := map[string]any{
		"stream_id": streamID,
	}

	return ws.callWeComAPI(ctx, token,
		"/cgi-bin/aibot/stream/send", reqBody)
}

// callStreamUpdate updates a stream message with new content.
// POST /cgi-bin/aibot/stream/update?access_token=TOKEN
func (ws *WeComSender) callStreamUpdate(
	ctx context.Context,
	token, streamID, content string,
	finish bool,
) error {
	if token == "" {
		return nil
	}

	reqBody := map[string]any{
		"stream_id": streamID,
		"finish":    finish,
		"msg_item": []map[string]any{
			{
				"msgtype": "text",
				"text": map[string]string{
					"content": content,
				},
			},
		},
	}

	return ws.callWeComAPI(ctx, token,
		"/cgi-bin/aibot/stream/update", reqBody)
}

// callWeComAPI makes a POST request to the WeCom API with the given
// JSON body.
func (ws *WeComSender) callWeComAPI(
	ctx context.Context,
	token, path string,
	body map[string]any,
) error {
	url := fmt.Sprintf(
		"https://qyapi.weixin.qq.com%s?access_token=%s",
		path, token)

	data, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("wecom: marshal api body: %w", err)
	}

	req, err := http.NewRequestWithContext(
		ctx, http.MethodPost, url, bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf(
			"wecom: create api request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := ws.client.Do(req)
	if err != nil {
		return fmt.Errorf(
			"wecom: api call %s: %w", path, err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	var apiResp struct {
		ErrCode int    `json:"errcode"`
		ErrMsg  string `json:"errmsg"`
	}
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return fmt.Errorf(
			"wecom: parse api response: %w", err)
	}

	if apiResp.ErrCode != 0 {
		return fmt.Errorf(
			"wecom: api error: code=%d, msg=%s",
			apiResp.ErrCode, apiResp.ErrMsg)
	}

	return nil
}

// sendProactiveReply sends a reply message to a WeCom response URL.
// response_url is provided by WeCom in the callback.
func (ws *WeComSender) sendProactiveReply(
	ctx context.Context,
	msg *gateway.GatewayMessage,
	content string,
) error {
	if msg.ResponseURL == "" || content == "" {
		return nil
	}

	reqBody := map[string]any{
		"msgtype": "text",
		"text": map[string]string{
			"content": content,
		},
	}

	data, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf(
			"wecom: marshal proactive reply: %w", err)
	}

	req, err := http.NewRequestWithContext(
		ctx, http.MethodPost, msg.ResponseURL,
		bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf(
			"wecom: create proactive reply: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := ws.client.Do(req)
	if err != nil {
		return fmt.Errorf(
			"wecom: send proactive reply: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf(
			"wecom: proactive reply failed: status=%d, body=%s",
			resp.StatusCode, string(respBody))
	}

	util.Logger.Debug("wecom: proactive reply sent")
	return nil
}

// generateStreamID creates a unique stream ID for streaming messages.
// In production, use a UUID; here we use the message ID with a prefix.
func generateStreamID(msg *gateway.GatewayMessage) string {
	return fmt.Sprintf("wukong_%s_%d", msg.MessageID, time.Now().UnixNano())
}
